### PR TITLE
Loosen telemetry version requirement

### PR DESCRIPTION
**Pull request by mcrumm**
Thanks for all the work that you're doing! When I tried to install your Phoenix fork w/ Bandit in an existing app with lots of dependencies, this was literally my only roadblock. Everything else Just Works™ 🎉 🚫 🤠

### CODE REVIEW

**Comment by mtrudel** [comment]
Looks good! I'm going to take a quick gander at the possible fallout in the morning but I don't suspect there will be any. To be clear, the issue was around a dependency your existing app had on telemetry and not anything in an otherwise new Phoenix app?

**Comment by mcrumm** [comment]
Correct! We have one older dependency that is pinned to telemetry `0.4.x` and I could probably update it, but most other dependencies are matching on either 0.4 or 1.0 as I've done here. Iirc the API had zero changes.

Thanks for your time!

**Comment by mtrudel** [comment]
Great to hear! Any issues with the functionality in your app moving to bandit? I'm still trying to figure out the best way to solicit issues / social proof from folks

**Comment by mcrumm** [comment]
I've only done a cursory local test so far, but everything appears to be working correctly– my LiveViews are requesting and receiving GraphQL subscription data over WebSockets in the usual way :D

**Comment by mtrudel** [comment]
Looking over https://github.com/beam-telemetry/telemetry/compare/v0.4.3..v1.0.0 you're correct! 

Thanks for the PR!

**Comment by mtrudel** [comment]
Published at 0.5.11, https://github.com/phoenixframework/phoenix/pull/4973's mix.lock also updated

**Pull request merged**
